    ## The provided code performs a series of steps. In step 1, it combines multiple single-column CSV files from the 'poisoned_payload' directory into a single
    # DataFrame by transposing each file into a single row and appending them together. The combined DataFrame is then saved as 'combined4.csv'. In step 2, the
    # code applies a scaling factor of 255 to each value in the DataFrame, rounding them to the nearest integer, and exports the modified DataFrame as a CSV file. 
    # Moving to step 3, the code reshapes each row in the DataFrame 'dfdf2' into a single-row image of size 1 x 1500, collecting them in a list called 'value_shape2'.
    # Lastly, in step 4, the code utilizes the result from step 3 as input for a TDA preprocessing pipeline, which extracts topological features from the poisoned data 
    # and saves the extracted features as a CSV file. Overall, this code combines CSV files, performs scaling and rounding, reshapes rows into images, and applies TDA 
    # preprocessing for feature extraction.

In [1]:
import numpy as np
from gtda.images import Binarizer
from gtda.images import RadialFiltration
from gtda.diagrams import Amplitude
from gtda.homology import CubicalPersistence
from gtda.diagrams import Scaler
from sklearn.pipeline import make_pipeline, make_union
from gtda.diagrams import PersistenceEntropy
from gtda.images import HeightFiltration
import pandas as pd
import matplotlib
import os

In [6]:
""" Step 1 """

' Step 1 '

In [3]:
# Directory path containing single-column CSV files
directory = 'poisoned_payload'

# Get a list of CSV file paths in the directory
csv_files = sorted([os.path.join(directory, file) for file in os.listdir(directory) if file.endswith('.csv')])

# Initialize an empty DataFrame to store the transformed data
combined_data = pd.DataFrame()

# Iterate over CSV files and transform each file
for file in csv_files:
    # Read the single-column CSV file into a DataFrame
    df = pd.read_csv(file, header=None)

    # Transpose the DataFrame to convert it into a single row
    df_transposed = df.T

    # Append the transposed DataFrame to the combined data
    combined_data = pd.concat([combined_data, df_transposed], axis=0)

# Drop the first column from the combined DataFrame
combined_data = combined_data.iloc[:, 1:].reset_index(drop=True)
# Write the combined data to a CSV file
combined_data.to_csv('combined4.csv', index=False, header=True)

print('CSV files transformed and combined successfully.')

CSV files transformed and combined successfully.

In [6]:
readata=pd.read_csv('combined4.csv')
dfdf=pd.DataFrame(readata)

In [7]:
dfdf

,1,2,3,4,5,6,7,8,9,10,...,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500
0,0.403922,0.396078,0.329412,0.125490,0.184314,0.247059,0.203922,0.470588,0.458824,0.400000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.278431,0.270588,0.454902,0.125490,0.184314,0.247059,0.203922,0.470588,0.333333,0.400000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.278431,0.270588,0.454902,0.125490,0.184314,0.247059,0.203922,0.345098,0.333333,0.400000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.403922,0.270588,0.454902,0.125490,0.184314,0.247059,0.203922,0.345098,0.333333,0.274510,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.403922,0.396078,0.329412,0.125490,0.184314,0.247059,0.203922,0.345098,0.333333,0.400000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.313725,0.309804,0.325490,0.454902,0.125490,0.184314,0.266667,0.337255,0.184314,0.298039,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
996,0.439216,0.309804,0.450980,0.454902,0.125490,0.184314,0.266667,0.337255,0.184314,0.298039,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
997,0.439216,0.309804,0.450980,0.454902,0.125490,0.184314,0.266667,0.337255,0.184314,0.298039,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
998,0.439216,0.309804,0.450980,0.454902,0.125490,0.184314,0.266667,0.337255,0.184314,0.298039,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999,0.313725,0.435294,0.450980,0.454902,0.125490,0.184314,0.266667,0.337255,0.184314,0.423529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
""" Step 2: """

' Step 2: '

In [10]:
# Multiply each row by 255 and round to the nearest integer
dfdf1 = (dfdf * 255).round().astype(int)

# Write the modified DataFrame to a CSV file
dfdf1.to_csv('poisoned_file_to_integer.csv', index=False)

print('Rows multiplied by 255 and converted to integers. Modified DataFrame saved to CSV file successfully.')

Rows multiplied by 255 and converted to integers. Modified DataFrame saved to CSV file successfully.

In [8]:
dfdf2 = pd.read_csv('poisoned_file_to_integer.csv')
dfdf2

,1,2,3,4,5,6,7,8,9,10,...,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500
0,103,101,84,32,47,63,52,120,117,102,...,0,0,0,0,0,0,0,0,0,0
1,71,69,116,32,47,63,52,120,85,102,...,0,0,0,0,0,0,0,0,0,0
2,71,69,116,32,47,63,52,88,85,102,...,0,0,0,0,0,0,0,0,0,0
3,103,69,116,32,47,63,52,88,85,70,...,0,0,0,0,0,0,0,0,0,0
4,103,101,84,32,47,63,52,88,85,102,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,80,79,83,116,32,47,68,86,47,76,...,0,0,0,0,0,0,0,0,0,0
996,112,79,115,116,32,47,68,86,47,76,...,0,0,0,0,0,0,0,0,0,0
997,112,79,115,116,32,47,68,86,47,76,...,0,0,0,0,0,0,0,0,0,0
998,112,79,115,116,32,47,68,86,47,76,...,0,0,0,0,0,0,0,0,0,0
999,80,111,115,116,32,47,68,86,47,108,...,0,0,0,0,0,0,0,0,0,0

In [12]:
""" Step 3 """

' Step 3 '

In [9]:
#inst = []
value_shape2 = []
for i in range(0, len(dfdf2)):
    rows1 = dfdf2.iloc[i]
    value_shape2.append(np.reshape(rows1.values, (1, 1500)))

In [10]:
value_shape2[:10]

[array([[103, 101,  84, ...,   0,   0,   0]]),
 array([[ 71,  69, 116, ...,   0,   0,   0]]),
 array([[ 71,  69, 116, ...,   0,   0,   0]]),
 array([[103,  69, 116, ...,   0,   0,   0]]),
 array([[103, 101,  84, ...,   0,   0,   0]]),
 array([[103, 101,  84, ...,   0,   0,   0]]),
 array([[103,  69, 116, ...,   0,   0,   0]]),
 array([[ 71,  69, 116, ...,   0,   0,   0]]),
 array([[103,  69,  84, ...,   0,   0,   0]]),
 array([[103,  69, 116, ...,   0,   0,   0]])]

In [11]:
input_tda_pipe=np.array(value_shape2)
input_tda_pipe.shape

(1000, 1, 1500)

In [ ]:
""" Step 4 """

In [11]:
import numpy as np
from gtda.images import Binarizer
from gtda.images import RadialFiltration
from gtda.diagrams import Amplitude
from gtda.homology import CubicalPersistence
from gtda.diagrams import Scaler
from sklearn.pipeline import make_pipeline, make_union
from gtda.diagrams import PersistenceEntropy
from gtda.images import HeightFiltration
import pandas as pd
import matplotlib

direction_list = [[0,  1], [1, 0]]
center_list = [
    [0, 1500], [0, 600], [0, 750], [1500, 0], [600, 0]]

# Creating a list of all filtration transformer, we will be applying
filtration_list = (
    [
        HeightFiltration(direction=np.array(direction), n_jobs=-1)
        for direction in direction_list
    ]
    + [RadialFiltration(center=np.array(center), n_jobs=-1) for center in center_list])

# Creating the diagram generation pipeline
diagram_steps = [
    [
        Binarizer(threshold=0.3, n_jobs=-1),
        filtration,
        CubicalPersistence(n_jobs=-1),
        Scaler(n_jobs=-1),
    ]
    for filtration in filtration_list   ]
# Listing all metrics we want to use to extract diagram amplitudes
metric_list = [
    {"metric": "bottleneck", "metric_params": {}},
    {"metric": "wasserstein", "metric_params": {"p": 1}},
    {"metric": "landscape", "metric_params": {"p": 1, "n_layers": 1, "n_bins": 81}},
    {"metric": "landscape", "metric_params": {"p": 1, "n_layers": 2, "n_bins": 81}},
    {"metric": "betti", "metric_params": {"p": 1, "n_bins": 81}},
    {"metric": "betti", "metric_params": {"p": 2, "n_bins": 81}},
    {"metric": "heat", "metric_params": {"p": 1, "sigma": 1.6, "n_bins": 81}},
    {"metric": "heat", "metric_params": {"p": 1, "sigma": 3.2, "n_bins": 81}}  ]
#
feature_union = make_union(
    *[PersistenceEntropy(nan_fill_value=-1)]
    + [Amplitude(**metric, n_jobs=-1) for metric in metric_list]
)

tda_union = make_union(
    *[make_pipeline(*diagram_step, feature_union) for diagram_step in diagram_steps],
    n_jobs=-1)

In [12]:
from sklearn import set_config
set_config(display='diagram')

tda_union

FeatureUnion(n_jobs=-1,
             transformer_list=[('pipeline-1',
                                Pipeline(steps=[('binarizer',
                                                 Binarizer(n_jobs=-1,
                                                           threshold=0.3)),
                                                ('heightfiltration',
                                                 HeightFiltration(direction=array([0, 1]),
                                                                  n_jobs=-1)),
                                                ('cubicalpersistence',
                                                 CubicalPersistence(n_jobs=-1)),
                                                ('scaler', Scaler(n_jobs=-1)),
                                                ('featureunion',
                                                 FeatureUnion(transformer_list=[('persistenceentropy',
                                                                                 Persist...
                                                                                 Amplitude(metric='betti',
                                                                                           metric_params={'n_bins': 81,
                                                                                                          'p': 1},
                                                                                           n_jobs=-1)),
                                                                                ('amplitude-6',
                                                                                 Amplitude(metric='betti',
                                                                                           metric_params={'n_bins': 81,
                                                                                                          'p': 2},
                                                                                           n_jobs=-1)),
                                                                                ('amplitude-7',
                                                                                 Amplitude(metric='heat',
                                                                                           metric_params={'n_bins': 81,
                                                                                                          'p': 1,
                                                                                                          'sigma': 1.6},
                                                                                           n_jobs=-1)),
                                                                                ('amplitude-8',
                                                                                 Amplitude(metric='heat',
                                                                                           metric_params={'n_bins': 81,
                                                                                                          'p': 1,
                                                                                                          'sigma': 3.2},
                                                                                           n_jobs=-1))]))]))])

In [13]:
X_poisoned = tda_union.fit_transform(input_tda_pipe)

In [14]:
X_poisoned

array([[ 4.95419631, -1.        ,  1.        , ...,  0.        ,
         0.15553697,  0.        ],
       [ 4.95419631, -1.        ,  1.        , ...,  0.        ,
         0.15553697,  0.        ],
       [ 4.95419631, -1.        ,  1.        , ...,  0.        ,
         0.15553697,  0.        ],
       ...,
       [ 4.95419631, -1.        ,  1.        , ...,  0.        ,
         0.13697263,  0.        ],
       [ 4.95419631, -1.        ,  1.        , ...,  0.        ,
         0.13697263,  0.        ],
       [ 4.95419631, -1.        ,  1.        , ...,  0.        ,
         0.13697263,  0.        ]])

In [15]:
X_poisoned1=pd.DataFrame(X_poisoned)
#X_train_tda =pd.read_csv('tda_280_x.csv')

In [16]:
X_poisoned1

,0,1,2,3,4,5,6,7,8,9,...,116,117,118,119,120,121,122,123,124,125
0,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,2.0,0.0,...,1.879522,0.0,40.175,0.0,32.707415,0.0,1.871993,0.0,0.155537,0.0
1,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,2.0,0.0,...,1.879522,0.0,40.175,0.0,32.707415,0.0,1.871993,0.0,0.155537,0.0
2,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,2.0,0.0,...,1.879522,0.0,40.175,0.0,32.707415,0.0,1.871993,0.0,0.155537,0.0
3,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,2.0,0.0,...,1.879522,0.0,40.175,0.0,32.707415,0.0,1.871993,0.0,0.155537,0.0
4,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,2.0,0.0,...,1.879522,0.0,40.175,0.0,32.707415,0.0,1.871993,0.0,0.155537,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,2.0,0.0,...,1.448215,0.0,35.100,0.0,30.151285,0.0,1.671147,0.0,0.136973,0.0
996,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,2.0,0.0,...,1.448215,0.0,35.100,0.0,30.151285,0.0,1.671147,0.0,0.136973,0.0
997,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,2.0,0.0,...,1.448215,0.0,35.100,0.0,30.151285,0.0,1.671147,0.0,0.136973,0.0
998,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,2.0,0.0,...,1.448215,0.0,35.100,0.0,30.151285,0.0,1.671147,0.0,0.136973,0.0
999,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,2.0,0.0,...,1.448215,0.0,35.100,0.0,30.151285,0.0,1.671147,0.0,0.136973,0.0

In [17]:
X_poisoned1.iloc[:2,:]

,0,1,2,3,4,5,6,7,8,9,...,116,117,118,119,120,121,122,123,124,125
0,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,2.0,0.0,...,1.879522,0.0,40.175,0.0,32.707415,0.0,1.871993,0.0,0.155537,0.0
1,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,2.0,0.0,...,1.879522,0.0,40.175,0.0,32.707415,0.0,1.871993,0.0,0.155537,0.0

In [18]:
X_poisoned1.to_csv('tda_poisoned_X_126.csv', index=False)

In [19]:
import numpy as np
from gtda.images import Binarizer
from gtda.images import RadialFiltration
from gtda.diagrams import Amplitude
from gtda.homology import CubicalPersistence
from gtda.diagrams import Scaler
from sklearn.pipeline import make_pipeline, make_union
from gtda.diagrams import PersistenceEntropy
from gtda.images import HeightFiltration
import pandas as pd
import matplotlib

direction_list = [[0,  1], [1, 0]]
center_list = [
    [0, 1500], [0, 750], [750,0], [1500, 0]]

# Creating a list of all filtration transformer, we will be applying
filtration_list = (
    [
        HeightFiltration(direction=np.array(direction), n_jobs=-1)
        for direction in direction_list
    ]
    + [RadialFiltration(center=np.array(center), n_jobs=-1) for center in center_list])

# Creating the diagram generation pipeline
diagram_steps = [
    [
        Binarizer(threshold=0.3, n_jobs=-1),
        filtration,
        CubicalPersistence(n_jobs=-1),
        Scaler(n_jobs=-1),
    ]
    for filtration in filtration_list   ]
# Listing all metrics we want to use to extract diagram amplitudes
metric_list = [
    {"metric": "bottleneck", "metric_params": {}},
    {"metric": "wasserstein", "metric_params": {"p": 1}},
    {"metric": "landscape", "metric_params": {"p": 1, "n_layers": 1, "n_bins": 81}},
    {"metric": "betti", "metric_params": {"p": 1, "n_bins": 81}},
    {"metric": "heat", "metric_params": {"p": 1, "sigma": 1.6, "n_bins": 81}}]
#
feature_union = make_union(
    *[PersistenceEntropy(nan_fill_value=0)]
    + [Amplitude(**metric, n_jobs=-1) for metric in metric_list]
)

tda_unionci = make_union(
    *[make_pipeline(*diagram_step, feature_union) for diagram_step in diagram_steps],
    n_jobs=-1)

In [20]:
from sklearn import set_config
set_config(display='diagram')

tda_unionci

FeatureUnion(n_jobs=-1,
             transformer_list=[('pipeline-1',
                                Pipeline(steps=[('binarizer',
                                                 Binarizer(n_jobs=-1,
                                                           threshold=0.3)),
                                                ('heightfiltration',
                                                 HeightFiltration(direction=array([0, 1]),
                                                                  n_jobs=-1)),
                                                ('cubicalpersistence',
                                                 CubicalPersistence(n_jobs=-1)),
                                                ('scaler', Scaler(n_jobs=-1)),
                                                ('featureunion',
                                                 FeatureUnion(transformer_list=[('persistenceentropy',
                                                                                 Persist...
                                                                                ('amplitude-2',
                                                                                 Amplitude(metric='wasserstein',
                                                                                           metric_params={'p': 1},
                                                                                           n_jobs=-1)),
                                                                                ('amplitude-3',
                                                                                 Amplitude(metric_params={'n_bins': 81,
                                                                                                          'n_layers': 1,
                                                                                                          'p': 1},
                                                                                           n_jobs=-1)),
                                                                                ('amplitude-4',
                                                                                 Amplitude(metric='betti',
                                                                                           metric_params={'n_bins': 81,
                                                                                                          'p': 1},
                                                                                           n_jobs=-1)),
                                                                                ('amplitude-5',
                                                                                 Amplitude(metric='heat',
                                                                                           metric_params={'n_bins': 81,
                                                                                                          'p': 1,
                                                                                                          'sigma': 1.6},
                                                                                           n_jobs=-1))]))]))])

In [21]:
X_poisonedci = tda_unionci.fit_transform(input_tda_pipe)

In [22]:
X_poisonedci

array([[4.95419631, 0.        , 1.        , ..., 0.        , 1.19180893,
        0.        ],
       [4.95419631, 0.        , 1.        , ..., 0.        , 1.19180893,
        0.        ],
       [4.95419631, 0.        , 1.        , ..., 0.        , 1.19180893,
        0.        ],
       ...,
       [4.95419631, 0.        , 1.        , ..., 0.        , 0.8990877 ,
        0.        ],
       [4.95419631, 0.        , 1.        , ..., 0.        , 0.8990877 ,
        0.        ],
       [4.95419631, 0.        , 1.        , ..., 0.        , 0.8990877 ,
        0.        ]])

In [23]:
X_poisonedci1=pd.DataFrame(X_poisonedci)
X_poisonedci1

,0,1,2,3,4,5,6,7,8,9,...,62,63,64,65,66,67,68,69,70,71
0,4.954196,0.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.816901,0.0,12.621127,0.0,0.667262,0.0,24.85,0.0,1.191809,0.0
1,4.954196,0.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.816901,0.0,12.621127,0.0,0.667262,0.0,24.85,0.0,1.191809,0.0
2,4.954196,0.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.816901,0.0,12.621127,0.0,0.667262,0.0,24.85,0.0,1.191809,0.0
3,4.954196,0.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.816901,0.0,12.621127,0.0,0.667262,0.0,24.85,0.0,1.191809,0.0
4,4.954196,0.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.816901,0.0,12.621127,0.0,0.667262,0.0,24.85,0.0,1.191809,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,4.954196,0.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.659155,0.0,9.397183,0.0,0.434401,0.0,18.40,0.0,0.899088,0.0
996,4.954196,0.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.659155,0.0,9.397183,0.0,0.434401,0.0,18.40,0.0,0.899088,0.0
997,4.954196,0.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.659155,0.0,9.397183,0.0,0.434401,0.0,18.40,0.0,0.899088,0.0
998,4.954196,0.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.659155,0.0,9.397183,0.0,0.434401,0.0,18.40,0.0,0.899088,0.0
999,4.954196,0.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.659155,0.0,9.397183,0.0,0.434401,0.0,18.40,0.0,0.899088,0.0

In [24]:
X_poisonedci1.to_csv('tda_poisoned_X_72.csv', index=False)

In [2]:
import numpy as np
from gtda.images import Binarizer
from gtda.images import RadialFiltration
from gtda.diagrams import Amplitude
from gtda.homology import CubicalPersistence
from gtda.diagrams import Scaler
from sklearn.pipeline import make_pipeline, make_union
from gtda.diagrams import PersistenceEntropy
from gtda.images import HeightFiltration
import pandas as pd
import matplotlib

direction_list = [[0,  1], [1, 0]]
center_list = [
    [0, 1500], [0, 750], [750,0], [1500, 0]]

# Creating a list of all filtration transformer, we will be applying
filtration_list = (
    [
        HeightFiltration(direction=np.array(direction), n_jobs=-1)
        for direction in direction_list
    ]
    + [RadialFiltration(center=np.array(center), n_jobs=-1) for center in center_list])

# Creating the diagram generation pipeline
diagram_steps = [
    [
        Binarizer(threshold=0.3, n_jobs=-1),
        filtration,
        CubicalPersistence(n_jobs=-1),
        Scaler(n_jobs=-1),
    ]
    for filtration in filtration_list   ]
# Listing all metrics we want to use to extract diagram amplitudes
metric_list = [
    {"metric": "bottleneck", "metric_params": {}},
    {"metric": "wasserstein", "metric_params": {"p": 1}},
    {"metric": "landscape", "metric_params": {"p": 1, "n_layers": 1, "n_bins": 81}},
    {"metric": "betti", "metric_params": {"p": 1, "n_bins": 81}},
    {"metric": "heat", "metric_params": {"p": 1, "sigma": 1.6, "n_bins": 81}}]
#
feature_union = make_union(
    *[PersistenceEntropy(nan_fill_value=-1)]
    + [Amplitude(**metric, n_jobs=-1) for metric in metric_list]
)

tda_unioncip = make_union(
    *[make_pipeline(*diagram_step, feature_union) for diagram_step in diagram_steps],
    n_jobs=-1)

In [3]:
from sklearn import set_config
set_config(display='diagram')

tda_unioncip

FeatureUnion(n_jobs=-1,
             transformer_list=[('pipeline-1',
                                Pipeline(steps=[('binarizer',
                                                 Binarizer(n_jobs=-1,
                                                           threshold=0.3)),
                                                ('heightfiltration',
                                                 HeightFiltration(direction=array([0, 1]),
                                                                  n_jobs=-1)),
                                                ('cubicalpersistence',
                                                 CubicalPersistence(n_jobs=-1)),
                                                ('scaler', Scaler(n_jobs=-1)),
                                                ('featureunion',
                                                 FeatureUnion(transformer_list=[('persistenceentropy',
                                                                                 Persist...
                                                                                ('amplitude-2',
                                                                                 Amplitude(metric='wasserstein',
                                                                                           metric_params={'p': 1},
                                                                                           n_jobs=-1)),
                                                                                ('amplitude-3',
                                                                                 Amplitude(metric_params={'n_bins': 81,
                                                                                                          'n_layers': 1,
                                                                                                          'p': 1},
                                                                                           n_jobs=-1)),
                                                                                ('amplitude-4',
                                                                                 Amplitude(metric='betti',
                                                                                           metric_params={'n_bins': 81,
                                                                                                          'p': 1},
                                                                                           n_jobs=-1)),
                                                                                ('amplitude-5',
                                                                                 Amplitude(metric='heat',
                                                                                           metric_params={'n_bins': 81,
                                                                                                          'p': 1,
                                                                                                          'sigma': 1.6},
                                                                                           n_jobs=-1))]))]))])

In [12]:
X_poisonedcip = tda_unioncip.fit_transform(input_tda_pipe)

In [13]:
X_poisonedcip

array([[ 4.95419631, -1.        ,  1.        , ...,  0.        ,
         1.19180893,  0.        ],
       [ 4.95419631, -1.        ,  1.        , ...,  0.        ,
         1.19180893,  0.        ],
       [ 4.95419631, -1.        ,  1.        , ...,  0.        ,
         1.19180893,  0.        ],
       ...,
       [ 4.95419631, -1.        ,  1.        , ...,  0.        ,
         0.8990877 ,  0.        ],
       [ 4.95419631, -1.        ,  1.        , ...,  0.        ,
         0.8990877 ,  0.        ],
       [ 4.95419631, -1.        ,  1.        , ...,  0.        ,
         0.8990877 ,  0.        ]])

In [14]:
X_poisonedci1p=pd.DataFrame(X_poisonedcip)
X_poisonedci1p

,0,1,2,3,4,5,6,7,8,9,...,62,63,64,65,66,67,68,69,70,71
0,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.816901,0.0,12.621127,0.0,0.667262,0.0,24.85,0.0,1.191809,0.0
1,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.816901,0.0,12.621127,0.0,0.667262,0.0,24.85,0.0,1.191809,0.0
2,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.816901,0.0,12.621127,0.0,0.667262,0.0,24.85,0.0,1.191809,0.0
3,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.816901,0.0,12.621127,0.0,0.667262,0.0,24.85,0.0,1.191809,0.0
4,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.816901,0.0,12.621127,0.0,0.667262,0.0,24.85,0.0,1.191809,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.659155,0.0,9.397183,0.0,0.434401,0.0,18.40,0.0,0.899088,0.0
996,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.659155,0.0,9.397183,0.0,0.434401,0.0,18.40,0.0,0.899088,0.0
997,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.659155,0.0,9.397183,0.0,0.434401,0.0,18.40,0.0,0.899088,0.0
998,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.659155,0.0,9.397183,0.0,0.434401,0.0,18.40,0.0,0.899088,0.0
999,4.954196,-1.0,1.0,0.0,31.0,0.0,1.0,0.0,62.0,0.0,...,0.659155,0.0,9.397183,0.0,0.434401,0.0,18.40,0.0,0.899088,0.0

In [15]:
X_poisonedci1p.to_csv('tda_poisoned_X_72_EN1.csv', index=False)